Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: filenne-infrastructure-${self:provider.stage}-user-pool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      VerificationMessageTemplate:
        DefaultEmailOption: "CONFIRM_WITH_CODE"
        EmailMessage: "<div style='background-color:#f4f4f4; padding: 10px;'><h2 style='color:#333;'>Welcome to Filenne</h2><p style='color:#666;'>Your verification code is: <strong>{####}</strong></p></div>"
        EmailSubject: "Filenne Infrastructure Verification Code"

  CognitoUserPoolDomain: 
    Type: AWS::Cognito::UserPoolDomain 
    Properties:
      UserPoolId:
        Ref: CognitoUserPool 
      Domain: "filenne-infrastructure-authorizer"

  CognitoUserPoolResourceServer: 
    Type: AWS::Cognito::UserPoolResourceServer
    Properties: 
      UserPoolId:
        Ref: CognitoUserPool
      Identifier: "api.filenne-infrastructure-authorizer.com" 
      Name: "filenne-infrastructure-resource-server" 
      Scopes: 
      - ScopeName: "filenne.health.read" 
        ScopeDescription: "Health endpoint for filenne-infrastructure service." 

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: filenne-infrastructure-user-app
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: true
      AllowedOAuthFlows: 
          - client_credentials
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - "api.filenne-infrastructure-authorizer.com/filenne.health.read"
