Resources:
  FilenneResourcesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.resourcesBucketName}-${self:provider.stage}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
  FilenneResourcesBucketAccessPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: FilenneResourcesBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: arn:aws:s3:::${self:custom.resourcesBucketName}-${self:provider.stage}/*

  FilenneFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.filesBucketName}-${self:provider.stage}
  FilenneFilesBucketAccessPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: FilenneFilesBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PresignedInteraction
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::${self:custom.config.${self:provider.stage}.accountId}:role/FilenneInfrastructureLambdaExecutionRole
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource:
              - arn:aws:s3:::${self:custom.filesBucketName}-${self:provider.stage}/*
              - arn:aws:s3:::${self:custom.filesBucketName}-${self:provider.stage}/*/*
          # - Sid: CloudFrontInteraction
          #   Effect: Allow
          #   Principal:
          #     Service: cloudfront.amazonaws.com
          #   Action:
          #     - s3:GetObject
          #     - s3:PutObject
          #   Resource:
          #     - arn:aws:s3:::${self:custom.filesBucketName}-${self:provider.stage}/*
          #     - arn:aws:s3:::${self:custom.filesBucketName}-${self:provider.stage}/*/*
          #   Condition:
          #     StringEquals:
          #       AWS:SourceArn:
          #         Fn::Sub: arn:aws:cloudfront::${self:custom.config.${self:provider.stage}.accountId}:distribution/${VaultBucketCloudFrontDistribution}
