Resources:
  CognitoClientCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /filenne/authorizer/client/credentials
      Description: Provides the secret key for cognito user pool
      GenerateSecretString:
        PasswordLength: 60
        ExcludeCharacters: '+%;"@/\'
        IncludeSpace: false
      Tags:
      - Key: Name
        Value: /filenne/authorizer/client/credentials
      - Key: managed-by
        Value: serverless

  CloudFrontKeyPairValues:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /filenne/infrastructure/cloudfront/keypair
      Description: Provides the secret key pair for AWS CloudFront distribution.
      SecretString: 
        Fn::Sub: |
          {
            "privateKey": "placeholder",
            "publicKey": "placeholder"
          }
      Tags:
      - Key: Name
        Value: /filenne/infrastructure/cloudfront/keypair
      - Key: managed-by
        Value: serverless