Resources:
  FilenneInfrastructureCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: filenne.io
      SubjectAlternativeNames:
        - 'api.filenne.io'
        - 'auth.filenne.io'
        - 'resources.filenne.io'
        - 'repo.filenne.io'
      ValidationMethod: DNS