Resources:
  FilenneResourcesBucketOriginAccess:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig: 
          Description: The origin access for S3 bucket resources.
          Name: FilenneResourcesBucketOriginAccess
          OriginAccessControlOriginType: s3
          SigningBehavior: always
          SigningProtocol: sigv4

  FilenneResourcesBucketCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - resources.filenne.io
        Origins:
          - DomainName: ${self:custom.resourcesBucketName}-${self:provider.stage}.s3.amazonaws.com
            Id: FilenneResourcesBucketCloudFrontDistribution
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId:
              Fn::GetAtt:
                - FilenneResourcesBucketOriginAccess
                - Id
        Enabled: "true"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: FilenneResourcesBucketCloudFrontDistribution
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn:
            Ref: FilenneCertificate
          SslSupportMethod: sni-only

# Repo cloudfront configurations
  FilenneRepoDistributionPublicKey:
    Type: AWS::CloudFront::PublicKey
    Properties:
      PublicKeyConfig:
        CallerReference: 'edebd2e7-57f5-42f8-90ea-5315a0233892'
        Name: 'FilenneRepoDistributionPublicKey'
        EncodedKey: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsBJvYG6InJG7CmjuU1av\nX5S5QLkhUdb3FOIOqFFkWqSF+PuR+zVYOjFqwMO7X1vPYF7ihUvsT220HcWqdA4k\nCgdHwu+fsT78gVy5NzE/v7MAEZ350EeaOCPumOjDACiSnBeY97Xfo8K1NfQ23iwW\ny7EDASmf8DQ4kTRfU6MxSM0+FbgDzP1E5Myl5olPK+Hxe5+y05dtMXkvRlIhB50M\n44U353Gyw1Xa/T0qmwgVyCspbZWH8OumEYqRWEulQ1oFspKuA94PDwzCtkdvRlSf\n15qvtoJMXd8BCkzoQFs70weJmJO1fQkTMHf1g8/St6uhpl26pFwXJvs87XO/ZiWy\ntwIDAQAB\n-----END PUBLIC KEY-----\n"
        Comment: 'Filenne repo cloudfront public key.'

  FilenneRepoDistributionKeyGroup:
    Type: AWS::CloudFront::KeyGroup
    Properties:
      KeyGroupConfig:
        Name: 'FilenneRepoDistributionKeyGroup'
        Items:
          - !Ref FilenneRepoDistributionPublicKey
        Comment: 'Filenne repo cloudfront key group.'

  FilenneRepoBucketOriginAccess:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig: 
          Description: The origin access for S3 vault bucket.
          Name: FilenneRepoBucketOriginAccess
          OriginAccessControlOriginType: s3
          SigningBehavior: always
          SigningProtocol: sigv4

  FilenneRepoBucketCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - repo.filenne.io
        Origins:
          - DomainName: ${self:custom.filesBucketName}-${self:provider.stage}.s3.amazonaws.com
            Id: FilenneRepoBucketCloudFrontDistribution
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId:
              Fn::GetAtt:
                - FilenneRepoBucketOriginAccess
                - Id
        Enabled: "true"
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          TrustedKeyGroups:
            - !Ref FilenneRepoDistributionKeyGroup
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: FilenneRepoBucketCloudFrontDistribution
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn:
            Ref: FilenneCertificate
          SslSupportMethod: sni-only